# Generated by Django 5.2.4 on 2025-10-30 16:46

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('full_time', 'Teljes munkaidős'), ('part_time', 'Részmunkaidős'), ('temporary', 'Beugrós'), ('seasonal', 'Szezonális'), ('internship', 'Gyakornoki'), ('contractor', 'Vállalkozói'), ('volunteer', 'Önkéntes')], max_length=20, unique=True, verbose_name='Munkaviszony kód')),
                ('name', models.CharField(max_length=50, verbose_name='Munkaviszony neve')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Leírás')),
            ],
            options={
                'verbose_name': 'Munkaviszony típus',
                'verbose_name_plural': 'Munkaviszony típusok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(0, 'Szabadnap'), (1, 'Délelőtt'), (10, 'Délután'), (11, 'Egész nap')], unique=True, verbose_name='Műszak kód')),
                ('name', models.CharField(max_length=50, verbose_name='Műszak neve')),
                ('short_name', models.CharField(max_length=5, verbose_name='Rövidítés')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Kezdési idő')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Befejezési idő')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Időtartam (óra)')),
                ('duration_days', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Időtartam (nap)')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Fizetett')),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Szín kód')),
            ],
            options={
                'verbose_name': 'Műszak típus',
                'verbose_name_plural': 'Műszak típusok',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('elso_ter', 'Első tér (pepita)'), ('fo_vendegter', 'Fő vendégtér'), ('terasz', 'Terasz'), ('hatso_ter', 'Hátsó tér'), ('konyha', 'Konyha'), ('bar', 'Bár'), ('kasszak', 'Kasszák'), ('mosogato', 'Mosogató'), ('takarito', 'Takarító')], max_length=20, unique=True, verbose_name='Terület kód')),
                ('name', models.CharField(max_length=100, verbose_name='Terület neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioritás')),
            ],
            options={
                'verbose_name': 'Munkaterület',
                'verbose_name_plural': 'Munkaterületek',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Személyzet')),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Felhasználó',
                'verbose_name_plural': 'Felhasználók',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Születési dátum')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Nem')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonszám')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Cím')),
                ('hire_date', models.DateField(blank=True, default=datetime.date(2025, 10, 30), null=True, verbose_name='Belépés dátuma')),
                ('min_full_shifts_per_month', models.IntegerField(blank=True, default=10, null=True, verbose_name='Min havi teljes műszakok összesen')),
                ('max_hours_per_day', models.IntegerField(blank=True, default=12, null=True, verbose_name='Max napi óraszám')),
                ('max_full_shifts_per_week', models.IntegerField(blank=True, default=5, null=True, verbose_name='Max heti teljes műszakok összesen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
                ('employment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.employmenttype', verbose_name='Munkaviszony típusa')),
            ],
            options={
                'verbose_name': 'Dolgozó',
                'verbose_name_plural': 'Dolgozók',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('request_data', models.JSONField(verbose_name='Igény adatok')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDayCell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('color', models.CharField(choices=[('green', 'Zöld'), ('red', 'Piros')], default='green', max_length=5)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fopincer', 'Főpincér'), ('pincer', 'Pincér'), ('pincerno', 'Pincérnő'), ('elso_kasszas', 'Első kasszás'), ('hatso_kasszas', 'Hátsó kasszás'), ('talalo', 'Tálaló'), ('teraszos', 'Teraszos'), ('mosogato', 'Mosogató'), ('takarito', 'Takarító'), ('eteles', 'Ételes'), ('elso_felvevo', 'Első felvevő'), ('hatso_felvevo', 'Hátsó felvevő'), ('kozepso_felvevo', 'Középső felvevő')], max_length=20, unique=True, verbose_name='Munkakör kód')),
                ('name', models.CharField(max_length=100, verbose_name='Munkakör neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Órabér')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('work_areas', models.ManyToManyField(to='apps.workarea', verbose_name='Munkaterületek')),
            ],
            options={
                'verbose_name': 'Munkakör',
                'verbose_name_plural': 'Munkakörök',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffSchedules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('schedule_data', models.JSONField(verbose_name='Beosztás adatok')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
            options={
                'verbose_name': 'Dolgozói beosztás összefoglaló',
                'verbose_name_plural': 'Dolgozói beosztás összefoglalók',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
