# Generated by Django 5.2.4 on 2025-09-30 21:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(0, 'Szabadnap'), (1, 'Délelőtt'), (10, 'Délután'), (11, 'Egész nap')], unique=True, verbose_name='Műszak kód')),
                ('name', models.CharField(max_length=50, verbose_name='Műszak neve')),
                ('short_name', models.CharField(max_length=5, verbose_name='Rövidítés')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Kezdési idő')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Befejezési idő')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Időtartam (óra)')),
                ('duration_days', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Időtartam (nap)')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Fizetett')),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Szín kód')),
            ],
            options={
                'verbose_name': 'Műszak típus',
                'verbose_name_plural': 'Műszak típusok',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('elso_ter', 'Első tér (pepita)'), ('fo_vendegter', 'Fő vendégtér'), ('terasz', 'Terasz'), ('hatso_ter', 'Hátsó tér'), ('konyha', 'Konyha'), ('bar', 'Bár'), ('kasszak', 'Kasszák'), ('mosogato', 'Mosogató'), ('takarito', 'Takarító')], max_length=20, unique=True, verbose_name='Terület kód')),
                ('name', models.CharField(max_length=100, verbose_name='Terület neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('priority', models.IntegerField(default=1, verbose_name='Prioritás')),
            ],
            options={
                'verbose_name': 'Munkaterület',
                'verbose_name_plural': 'Munkaterületek',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('vezeto', 'Vezető'), ('dolgozo', 'Dolgozó'), ('pincer', 'Pincér'), ('pincerno', 'Pincérnő'), ('elso_kasszas', 'Első kasszás'), ('hatso_kasszas', 'Hátsó kasszás'), ('talalo', 'Tálaló'), ('terasz_pincer', 'Terasz pincér'), ('terasz_pincerno', 'terasz pincérnő'), ('eteles', 'Ételes'), ('elso_felvevo', 'Első felvevő'), ('hatso_felvevo', 'Hátsó felvevő'), ('kozepso_felvevo', 'Középső felvevő')], default='dolgozo', max_length=20, verbose_name='Szerepkör')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Személyzet')),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Felhasználó',
                'verbose_name_plural': 'Felhasználók',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True, verbose_name='Dolgozó azonosító')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Születési dátum')),
                ('gender', models.CharField(blank=True, choices=[('F', 'Nő'), ('M', 'Férfi'), ('O', 'Egyéb')], max_length=1, verbose_name='Nem')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefonszám')),
                ('address', models.TextField(blank=True, verbose_name='Cím')),
                ('hire_date', models.DateField(verbose_name='Belépés dátuma')),
                ('is_full_time', models.BooleanField(default=True, verbose_name='Teljes munkaidős')),
                ('max_hours_per_week', models.IntegerField(default=40, verbose_name='Max heti óraszám')),
                ('max_days_per_week', models.IntegerField(default=6, verbose_name='Max heti napok')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Segélyhívó neve')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Segélyhívó telefonja')),
                ('excel_code', models.CharField(blank=True, max_length=10, verbose_name='Excel kód (pl. BGJ)')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
                ('primary_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workarea', verbose_name='Elsődleges munkaterület')),
            ],
            options={
                'verbose_name': 'Dolgozó',
                'verbose_name_plural': 'Dolgozók',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('name', models.CharField(max_length=100, verbose_name='Beosztás neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás dátuma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítás dátuma')),
                ('status', models.CharField(choices=[('draft', 'Tervezet'), ('in_review', 'Felülvizsgálat alatt'), ('approved', 'Jóváhagyott'), ('published', 'Közzétett'), ('archived', 'Archivált')], default='draft', max_length=20, verbose_name='Státusz')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Jóváhagyás dátuma')),
                ('total_assignments', models.IntegerField(default=0, verbose_name='Összes beosztás')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Összes munkaóra')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Jóváhagyta')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozta')),
            ],
            options={
                'verbose_name': 'Havi beosztás',
                'verbose_name_plural': 'Havi beosztások',
                'ordering': ['-year', '-month', 'name'],
                'unique_together': {('year', 'month', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(default=0, verbose_name='Összes dolgozó')),
                ('total_work_days', models.IntegerField(default=0, verbose_name='Összes munkanap')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Összes munkaóra')),
                ('morning_shifts', models.IntegerField(default=0, verbose_name='Délelőtti műszakok')),
                ('afternoon_shifts', models.IntegerField(default=0, verbose_name='Délutáni műszakok')),
                ('full_day_shifts', models.IntegerField(default=0, verbose_name='Egész napos műszakok')),
                ('free_days', models.IntegerField(default=0, verbose_name='Szabadnapok')),
                ('avg_hours_per_employee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Átlag óra/dolgozó')),
                ('avg_days_per_employee', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Átlag nap/dolgozó')),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Becsült összes költség')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Számítás dátuma')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.monthlyschedule', verbose_name='Havi beosztás')),
            ],
            options={
                'verbose_name': 'Beosztás statisztika',
                'verbose_name_plural': 'Beosztás statisztikák',
            },
        ),
        migrations.CreateModel(
            name='EmployeePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('availability', 'Elérhetőség'), ('unavailability', 'Nem elérhető'), ('preferred_shift', 'Preferált műszak'), ('preferred_area', 'Preferált munkaterület'), ('max_consecutive_days', 'Max egymás utáni napok'), ('min_rest_days', 'Min pihenőnapok'), ('special_request', 'Speciális kérés'), ('recurring_pattern', 'Ismétlődő minta'), ('excel_note', 'Excel megjegyzés')], max_length=30, verbose_name='Preferencia típus')),
                ('priority', models.CharField(choices=[('low', 'Alacsony'), ('medium', 'Közepes'), ('high', 'Magas'), ('critical', 'Kritikus')], default='medium', max_length=10, verbose_name='Prioritás')),
                ('color_code', models.CharField(choices=[('green', 'Zöld - Rugalmas'), ('blue', 'Kék - Várható'), ('orange', 'Narancs - Fix de mozgatható'), ('red', 'Piros - Mozgatthatatlan')], default='green', max_length=10, verbose_name='Szín kód')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Konkrét dátum')),
                ('day_of_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Hónap napja')),
                ('day_of_week', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Hét napja')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Kezdő dátum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Befejező dátum')),
                ('excel_original_text', models.TextField(blank=True, verbose_name='Eredeti Excel szöveg')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Feldolgozott adatok')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Ismétlődő')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.monthlyschedule', verbose_name='Havi beosztás')),
                ('preferred_shift_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.shifttype', verbose_name='Preferált műszak')),
                ('preferred_work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workarea', verbose_name='Preferált munkaterület')),
            ],
            options={
                'verbose_name': 'Dolgozói preferencia',
                'verbose_name_plural': 'Dolgozói preferenciák',
                'ordering': ['-priority', 'employee', 'specific_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('pincer', 'Pincér'), ('pincerno', 'Pincérnő'), ('elso_kasszas', 'Első kasszás'), ('hatso_kasszas', 'Hátsó kasszás'), ('talalo', 'Tálaló'), ('teraszos', 'Teraszos'), ('mosogato', 'Mosogató'), ('takarito', 'Takarító'), ('eteles', 'Ételes'), ('elso_felvevo', 'Első felvevő'), ('hatso_felvevo', 'Hátsó felvevő'), ('kozepso_felvevo', 'Középső felvevő')], max_length=20, unique=True, verbose_name='Munkakör kód')),
                ('name', models.CharField(max_length=100, verbose_name='Munkakör neve')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Órabér')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('work_areas', models.ManyToManyField(to='apps.workarea', verbose_name='Munkaterületek')),
            ],
            options={
                'verbose_name': 'Munkakör',
                'verbose_name_plural': 'Munkakörök',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='work_roles',
            field=models.ManyToManyField(to='apps.workrole', verbose_name='Munkakörök'),
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Nap')),
                ('notes', models.TextField(blank=True, verbose_name='Megjegyzések')),
                ('is_overtime', models.BooleanField(default=False, verbose_name='Túlóra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.monthlyschedule', verbose_name='Havi beosztás')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.shifttype', verbose_name='Műszak típus')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workarea', verbose_name='Munkaterület')),
            ],
            options={
                'verbose_name': 'Beosztás hozzárendelés',
                'verbose_name_plural': 'Beosztás hozzárendelések',
                'ordering': ['schedule', 'day', 'employee'],
                'unique_together': {('schedule', 'employee', 'day')},
            },
        ),
    ]
