# Generated by Django 5.2.4 on 2025-10-07 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepreference',
            name='preference_type',
            field=models.CharField(choices=[('availability', 'Elérhetőség'), ('unavailability', 'Nem elérhető'), ('preferred_shift', 'Preferált műszak'), ('preferred_area', 'Preferált munkaterület'), ('max_consecutive_days', 'Max egymás utáni napok'), ('min_rest_days', 'Min pihenőnapok'), ('special_request', 'Speciális kérés'), ('recurring_pattern', 'Ismétlődő minta'), ('excel_note', 'Excel megjegyzés')], default='availability', max_length=30, verbose_name='Preferencia típus'),
        ),
        migrations.CreateModel(
            name='EmployeeRequests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('request_data', models.JSONField(verbose_name='Igény adatok')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
        ),
    ]
