# Generated by Django 5.2.4 on 2025-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_employeepreference_preference_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('color', models.CharField(choices=[('green', 'Zöld'), ('red', 'Piros')], default='green', max_length=5)),
            ],
        ),
    ]
