# Generated by Django 5.2.4 on 2025-11-03 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 3), null=True, verbose_name='Belépés dátuma'),
        ),
    ]
