# Generated by Django 5.2.4 on 2025-10-15 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_daycell'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycell',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó'),
        ),
        migrations.AlterField(
            model_name='daycell',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
