# Generated by Django 5.2.4 on 2025-10-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_daycell_employee_alter_daycell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycell',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó'),
        ),
    ]
