# Generated by Django 5.2.4 on 2025-11-17 19:21

import datetime
import django.db.models.deletion
from django.db import migrations, models

from apps.models import WorkRole


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('sick_leave', 'Betegség'), ('vacation', 'Szabadság'), ('unpaid_leave', 'Fizetés nélküli szabadság'), ('maternity_leave', 'Gyes/Gyed'), ('meeting', 'Munkatársi megbeszélés'), ('lecture', 'Előadás/közösségi nap'), ('training', 'Képzés'), ('other', 'Egyéb')], max_length=20, unique=True, verbose_name='Hiányzás kód')),
                ('name', models.CharField(max_length=50, verbose_name='Hiányzás neve')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Leírás')),
            ],
            options={
                'verbose_name': 'Hiányzás típus',
                'verbose_name_plural': 'Hiányzás típusok',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='default_work_role',
            field=models.ForeignKey(blank=True, default=WorkRole.objects.filter(code='talalo').first(), null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workrole', verbose_name='Alapértelmezett munkakör'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 17), null=True, verbose_name='Belépés dátuma'),
        ),
        migrations.AddField(
            model_name='employee',
            name='absence_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.absencetype', verbose_name='Hiányzás típusa'),
        ),
        migrations.DeleteModel(
            name='ScheduleDayCell',
        ),
    ]
