# Generated by Django 5.2.4 on 2025-11-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_absencetype_employee_default_work_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='default_work_role',
            field=models.ForeignKey(blank=True, default='talalo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workrole', verbose_name='Alapértelmezett munkakör'),
        ),
    ]
