# Generated by Django 5.2.4 on 2025-10-15 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_daycell_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycell',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó'),
        ),
    ]
