# Generated by Django 5.2.4 on 2025-11-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_employee_default_work_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workarea',
            options={'ordering': ['name'], 'verbose_name': 'Munkaterület', 'verbose_name_plural': 'Munkaterületek'},
        ),
        migrations.RemoveField(
            model_name='workarea',
            name='priority',
        ),
        migrations.AlterField(
            model_name='employee',
            name='default_work_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.workrole', verbose_name='Alapértelmezett munkakör'),
        ),
    ]
