# Generated by Django 5.2.4 on 2025-10-18 11:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_daycell_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDayCell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('color', models.CharField(choices=[('green', 'Zöld'), ('red', 'Piros')], default='green', max_length=5)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSchedules',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('schedule_data', models.JSONField(verbose_name='Beosztás adatok')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.employee', verbose_name='Dolgozó')),
            ],
            options={
                'verbose_name': 'Dolgozói beosztás összefoglaló',
                'verbose_name_plural': 'Dolgozói beosztás összefoglalók',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
