# Generated by Django 5.2.4 on 2025-11-18 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_delete_workrole_work_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrole',
            name='work_areas',
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 18), null=True, verbose_name='Belépés dátuma'),
        ),
        migrations.AlterField(
            model_name='workarea',
            name='code',
            field=models.CharField(choices=[('elso_ter', 'Első tér (pepita)'), ('fo_vendegter', 'Fő vendégtér'), ('terasz', 'Terasz'), ('hatso_ter', 'Hátsó tér'), ('konyha', 'Konyha'), ('bar', 'Bár'), ('kasszak', 'Kasszák'), ('mosogato', 'Mosogató'), ('takarito', 'Takarító')], default='fo_vendegter', max_length=20, unique=True, verbose_name='Terület kód'),
        ),
    ]
