# Generated by Django 5.2.4 on 2025-11-22 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_workrole_work_areas_alter_employee_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 11, 22), null=True, verbose_name='Belépés dátuma'),
        ),
        migrations.AlterField(
            model_name='workrole',
            name='code',
            field=models.CharField(choices=[('fopincer', 'Főpincér'), ('elso_kasszas', 'Első kasszás'), ('hatso_kasszas', 'Hátsó kasszás'), ('felszolgalo', 'Felszolgáló'), ('mosogato', 'Mosogató'), ('elviteles', 'Elviteles'), ('vendeg_fogado', 'Vendégfogadó'), ('teraszos', 'Teraszos')], max_length=20, unique=True, verbose_name='Munkakör kód'),
        ),
    ]
