# Generated by Django 5.2.4 on 2025-11-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_employee_hire_date_alter_workrole_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrole',
            name='code',
            field=models.CharField(choices=[('fopincer', 'Főpincér'), ('elso_kasszas', 'Első kasszás'), ('hatso_kasszas', 'Hátsó kasszás'), ('felszolgalo', 'Felszolgáló'), ('elviteles', 'Elviteles'), ('vendeg_fogado', 'Vendégfogadó'), ('teraszos', 'Teraszos')], max_length=20, unique=True, verbose_name='Munkakör kód'),
        ),
    ]
