# Generated by Django 5.2.4 on 2025-12-06 23:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_workrole_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 12, 7), null=True, verbose_name='Belépés dátuma'),
        ),
        migrations.CreateModel(
            name='RequiredStaffing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Év')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Hónap')),
                ('staffing_data', models.JSONField(verbose_name='Szükséges létszám minimumok műszakonként')),
            ],
            options={
                'verbose_name': 'Szükséges létszám műszakonkénti létszám minimum havonta',
                'verbose_name_plural': 'Szükséges létszám műszakonkénti létszám minimum havonta',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
