# Generated by Django 5.2.4 on 2025-12-08 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_employee_hire_date_requiredstaffing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 12, 8), null=True, verbose_name='Belépés dátuma'),
        ),
    ]
